### ISSUE TITLE
Run on UI thread call issues (Windows?)

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains/JWM#110]
- [ ] Windows: fix user lambda calls

![image](https://user-images.githubusercontent.com/31863304/129883968-85b993ea-7d5a-437f-82ce-6fb40af79dd9.png)

**Comment by EgorOrachyov** [comment]
Building jwm_x64.dll
-- Java home found by JAVA_HOME env variable: C:\Program Files\OpenJDK\jdk-16
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/egoro/Documents/GitHub/JWM/windows/build
ninja: no work to do.
Loading C:\Users\egoro\Documents\GitHub\JWM\windows\build\jwm_x64.dll
Screens:
  Screen(_id=65537, _x=0, _y=0, _width=3840, _height=2160, _scale=2.5, _isPrimary=true)
LayerWGL.cc:135 Create GL layer for window 0x000001CEFBF7CEE0
WindowWin32.cc:79 Set window position left=250 top=250
WindowWin32.cc:174 Move event left=250 top250
WindowWin32.cc:88 Set window size w=2000 h=1500
WindowWin32.cc:161 Size event window w=2000 h=1500 content w=1968 h=1412
WindowWin32.cc:161 Size event window w=2000 h=1500 content w=1968 h=1412
WindowWin32.cc:174 Move event left=250 top250
Timer paint
Timer paint
WindowWin32.cc:444 Event close
LayerWGL.cc:162 Close GL layer for window 0x000001CEFBF7CEE0
Timer paint
WARNING in native method: JNI call made with exception pending
        at org.jetbrains.jwm.App._nStart(Native Method)
        at org.jetbrains.jwm.App.start(App.java:51)
        at org.jetbrains.jwm.examples.Example.main(Example.java:498)
java.lang.RuntimeException: Can't wrap nullptr
        at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
        at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8)
        at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:110)
        at org.jetbrains.skija.DirectContext.makeGL(DirectContext.java:13)
        at org.jetbrains.jwm.examples.SkijaLayerGL.beforePaint(SkijaLayerGL.java:14)
        at org.jetbrains.jwm.examples.Example.paint(Example.java:73)
        at org.jetbrains.jwm.examples.Example$1.lambda$run$0(Example.java:61)
        at org.jetbrains.jwm.App._nStart(Native Method)
        at org.jetbrains.jwm.App.start(App.java:51)
        at org.jetbrains.jwm.examples.Example.main(Example.java:498)
Exception in thread "main" java.lang.RuntimeException: Can't wrap nullptr
        at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
        at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8)
        at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:110)
        at org.jetbrains.skija.DirectContext.makeGL(DirectContext.java:13)
        at org.jetbrains.jwm.examples.SkijaLayerGL.beforePaint(SkijaLayerGL.java:14)
        at org.jetbrains.jwm.examples.Example.paint(Example.java:73)
        at org.jetbrains.jwm.examples.Example$1.lambda$run$0(Example.java:61)
        at org.jetbrains.jwm.App._nStart(Native Method)
        at org.jetbrains.jwm.App.start(App.java:51)
        at org.jetbrains.jwm.examples.Example.main(Example.java:498)
Traceback (most recent call last):
  File "C:\Users\egoro\Documents\GitHub\JWM\script\run.py", line 65, in <module>
    sys.exit(main())
  File "C:\Users\egoro\Documents\GitHub\JWM\script\run.py", line 50, in main
    subprocess.check_call([
  File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '--class-path', 'C:\\Users\\egoro\\.m2\\repository\\org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar;C:\\Users\\egoro\\.m2\\repository\\org/jetbrains/annotations/20.1.0/annotations-20.1.0.jar;shared/target/classes;windows/build;windows/target/classes;C:\\Users\\egoro\\.m2\\repository\\org/jetbrains/skija/skija-shared/0.92.22/skija-shared-0.92.22.jar;C:\\Users\\egoro\\.m2\\repository\\org/jetbrains/skija/skija-windows/0.92.22/skija-windows-0.92.22.jar;examples/target/classes', '-Djava.awt.headless=true', '-enableassertions', '-enablesystemassertions', '-Dfile.encoding=UTF-8', '-Xcheck:jni', 'org.jetbrains.jwm.examples.Example']' returned non-zero exit status 1.
